a = int(input("please enter number 1 "))
b = int(input("please enter number 2 "))

print("addition is ", a+b)
print("substraction is ", a-b)
print("multiplication is ", a*b)
print("division is ", a/b )
print("exponentiation is ", a**b)
print("floor division is ", a//b)
print("modulus is ", a%b)
